from __future__ import annotations

from typing import Any

from shortjob_runner.types import Condition, SYNC_POLICY
from shortjob_runner.workloads import StepWorkload


def base_result(
    condition: Condition,
    workload: StepWorkload,
    machine: dict[str, Any],
    gpu: dict[str, Any],
    runtime: dict[str, Any],
    started_at_utc: str,
    condition_order_seed: int,
    randomized_order: bool,
    num_repeats_planned: int,
    time_accounting_mode: str,
    cache_state: str,
) -> dict[str, Any]:
    return {
        "run_id": (
            f"{condition.workload_id}-{condition.action}"
            f"-b{condition.batch_size}-s{condition.num_steps}-r{condition.repeat:02d}"
        ),
        "workload_id": condition.workload_id,
        "action": condition.action,
        "repeat": condition.repeat,
        "status": "completed",
        "machine": machine,
        "gpu": gpu,
        "runtime": runtime,
        "schema_version": "shortjob_raw_v2",
        "started_at_utc": started_at_utc,
        "finished_at_utc": None,
        "condition_order_seed": condition_order_seed,
        "task_family": workload.spec.task_family,
        "workload_class": workload.spec.workload_class,
        "shape_stability": workload.spec.shape_stability,
        "application": workload.spec.application,
        "bottleneck_hypothesis": workload.spec.bottleneck_hypothesis,
        "preferred_metric": workload.spec.preferred_metric,
        "supports_cpu": workload.spec.supports_cpu,
        "supports_cuda_graph": workload.spec.supports_cuda_graph,
        "supports_training": workload.spec.supports_training,
        "supports_mixed_precision": workload.spec.supports_mixed_precision,
        "batch_size": condition.batch_size,
        "num_steps": condition.num_steps,
        "input_mode": workload.spec.input_mode,
        "execution_device": None,
        "requested_device": None,
        "action_variant": condition.action,
        "compile_mode": None,
        "precision_mode": None,
        "tf32_enabled": False,
        "micro_batch_factor": None,
        "model_init_runtime_s": None,
        "cuda_context_init_s": None,
        "total_runtime_s": None,
        "cold_total_runtime_s": None,
        "warm_cached_total_runtime_s": None,
        "warmup_runtime_s": None,
        "measured_runtime_s": None,
        "device_event_runtime_s": None,
        "compile_call_overhead_s": None,
        "compile_overhead_s": None,
        "graph_capture_overhead_s": None,
        "graph_warmup_runtime_s": None,
        "graph_instantiate_runtime_s": None,
        "input_copy_overhead_s": None,
        "input_copy_bytes": None,
        "avg_step_time_ms": None,
        "median_step_time_ms": None,
        "p50_step_time_ms": None,
        "p90_step_time_ms": None,
        "p95_step_time_ms": None,
        "p99_step_time_ms": None,
        "throughput_per_s": None,
        "first_k_steps": None,
        "first_k_eager_step_time_ms": None,
        "first_k_step_time_variance_ms": None,
        "time_accounting_mode": time_accounting_mode,
        "cache_state": cache_state,
        "sync_policy": SYNC_POLICY,
        "randomized_order": randomized_order,
        "num_repeats_planned": num_repeats_planned,
        "compile_failed": False,
        "precheck_failed": False,
        "capture_failed": False,
        "graph_break_detected": False,
        "recompile_detected": False,
        "fallback_to_eager": False,
        "failure_reason": None,
        "peak_gpu_memory_mb": None,
        "avg_gpu_utilization": None,
        "env_snapshot_before": None,
        "env_snapshot_after": None,
        "power_limit_lock": None,
        "oom": False,
        "num_successful_steps": 0,
        "relative_gain_vs_eager": None,
        "relative_gain_vs_eager_baseline": None,
        "relative_gain_vs_literal_eager": None,
        "eager_baseline_action": None,
        "eager_baseline_total_runtime_s": None,
        "literal_eager_total_runtime_s": None,
        "excess_vs_eager_baseline_s": None,
        "normalized_excess_vs_eager_baseline": None,
        "missed_benefit_vs_eager_baseline_s": None,
        "is_best_action": None,
        "regret_vs_oracle_s": None,
        "normalized_regret_vs_oracle": None,
        "wrong_enable": None,
        "missed_opportunity": None,
        "action_feasible": None,
    }


def apply_total_time(result: dict[str, Any], total_runtime_s: float, time_accounting_mode: str) -> None:
    result["total_runtime_s"] = round(total_runtime_s, 6)
    if time_accounting_mode == "cold_total":
        result["cold_total_runtime_s"] = result["total_runtime_s"]
    elif time_accounting_mode == "warm_cached_total":
        result["warm_cached_total_runtime_s"] = result["total_runtime_s"]
